### ISSUE TITLE
公欠の詳細情報の表示

### ISSUE THREAD

**Issue by nama1118** [nama1118/holidoys_system#17]
公欠の詳細情報を管理者ページから見られるようにする

- [x] 管理者ページに詳細ページに行くためのリンクを付ける
- [x] 詳細画面のページを作る
- [x] 詳細画面に公欠の情報を全て表示する

**Comment by mikanyo-guruto** [comment]
詳細画面でのエラー改善できないので明日またお伺いします。
---内容---
・findByIdで一つ(?）しか情報を持ってきていないのに、foreachで回したとき変なところを読み込んでいる。
・詳細画面でのリレーションが効いていない。
・データベース設定の間違いかDATETIMEがNULLになる。

**Comment by mikanyo-guruto** [comment]
解決しました。
