### ISSUE TITLE
saveについての質問

### ISSUE THREAD

**Issue by mikanyo-guruto** [nama1118/holidoys_system#25]
今回、校欠日を"月"と"日"に分けて登録していますが
そこでデータベースのpublic_holidayにどう登録すればいいか分かりません。
一応自分のブランチにあげてある最新のコミットでは、saveはできるのですが、
public_holidayに登録しても全て0として登録されてしまいます。

お手数ですがよろしくお願いします。

**Comment by nama1118** [comment]
えーっと…datetimeの形式で保存できないとダメだね
http://php.net/manual/ja/class.datetime.php

**Comment by nama1118** [comment]
なので上手いこと月と日を取り出して指定のフォーマットにしてあげないとダメかな
上記URLの関数でdatetimeを作ってくれるような関数があったり、datetimeの形式に変換できれば問題は解決すると思います

**Comment by mikanyo-guruto** [comment]
dateフォーマットに直したら送信したら解決しました。
ありがとうございます。
