### ISSUE TITLE
発表までにやること

### ISSUE THREAD

**Issue by mikanyo-guruto** [nama1118/holidoys_system#28]
- [x] パスワードを暗号化し登録
- [x] ユーザー画面のデザインの向上
- [x] ファイルとプログラムの掃除

- [x] ヴァリデーションチェック

**Comment by nama1118** [comment]
一応、ここに

今回は管理者の追加機能は実装しないので
> パスワードを暗号化し登録

の作業はとりあえず必要ないです

いつかパスワードを保存する時が来た時の為に書いておきますが
パスワードを平文（元のままの文字列）で保存するのはセキュリティリスクです
理由は万が一データベースのデータをみられた時にパスワードが平文だとそれだけで完全なパスワードが流出するからです
他にも、データを確認している人の横から悪意のある人が画面を見たらわかる（もちろん悪意があるないにしろ、確認している人自体も対象ですが）ということ

とにかく、こういったデータはハッシュで保存するということで対応する必要があります
参考になりそうなのは
http://kwski.net/cakephp-2-x/1132/
…cakephpはちょっと癖が強い感じ…規則が堅いというか。

passwordhashという関数もあります（PHPのバージョンに注意　PHP 5 >= 5.5.0, PHP 7）
http://php.net/manual/ja/function.password-hash.php

これらを使ってパスワードを一度ハッシュにしてから保存します
そうすればとりあえずは上記の問題は解決します（そもそもデータが見れる時点でアウトっちゃーアウトですが、被害を少なくするという目的では達成されてます）

どうやってパスワードを確認するんだというところでは
「入力されたパスワードをハッシュ化したもの」と「ハッシュ化されているデータベースのデータ」で確認します。

例えば「hoge」のハッシュ化したデータが「31f30ddbcb1bf8446576f0e64aa4c88a9f055e3c」とします
このハッシュ化の結果は「hoge」であれば必ず「31f30ddbcb1bf8446576f0e64aa4c88a9f055e3c」というユニークなものになるので、if文での確認が可能です。
